SELECT ESPECIE.ESP_NOMBRE,
	ESPECIE.ESP_SEXO,
	LOC.LOC_PARQUE_NACIONAL,
	LOC.GEOM,
	PRO.PRO_NOMBRE,
	PA.PAS_NOMBRE,
	IDE.IDE_APELLIDO,
	IDE.IDE_ANIO,
	COL.COL_APELLIDO,
	COL.COL_FECHA,
	COL.COL_METODO,
	COL.COL_DESTINO
FROM ESPECIE -- union especie - ubicacion
INNER JOIN LOCALIZACION AS LOC ON ESPECIE.ESP_ID = LOC.ESP_ID
INNER JOIN LOCALIZACION_PROVINCIA AS LOC_PRO ON LOC.LOC_ID = LOC_PRO.LOC_ID
INNER JOIN PROVINCIA AS PRO ON LOC_PRO.PRO_ID = PRO.PRO_ID
INNER JOIN PAIS AS PA ON PRO.PAS_ID = PA.PAS_ID -- union especie - identificador
INNER JOIN ESPECIE_IDENTIFICADOR AS ESP_IDE ON ESPECIE.ESP_ID = ESP_IDE.ESP_ID
INNER JOIN IDENTIFICADOR AS IDE ON ESP_IDE.IDE_ID = IDE.IDE_ID -- union especie - colector
INNER JOIN ESPECIE_COLECTOR AS ESP_COL ON ESPECIE.ESP_ID = ESP_COL.ESP_ID
INNER JOIN COLECTOR AS COL ON ESP_COL.COL_ID = COL.COL_ID -- union especie - referencia

WHERE PRO.PRO_NOMBRE = 'Pichincha'